services:
  postgres:
    image: postgres
    container_name: football-db1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: football_booking01
    ports:
      - "5433:5433"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d   # ใช้ไฟล์ .sql ในโฟลเดอร์นี้
      - postgres_data:/var/lib/postgresql/data  # ใช้ Docker volume จริง
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_football
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
